### ISSUE TITLE
Scaffolding error

### ISSUE THREAD

**Issue by DFectuoso** [latteware/marble-seed#100]
When using node tasks/scaffolding/admin/scaffold-admin

If i answer "y" to "Field 2 is Array of objects?:", the scaffold fails with the next error:

I get:
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn standard ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by DFectuoso** [comment]
Actually it also fails if it is not an array:

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn standard ENOENT
    at _errnoException (util.js:1041:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by DFectuoso** [comment]
The scaffolding fails if i don't have https://standardjs.com/ installed with npm install -g standard, probably need to safeguard that
